### ISSUE TITLE
Battery icon resets when switching to landscape on Pixel Experience 12.1

### ISSUE THREAD

**Issue by TheFeelTrain** [siavash79/AOSPMods#329]
**Describe the bug**

As the title says, the battery icon resets seemingly at random. It lasts a few minutes and then will change back to the default. You can see in the screenshot I've selected Circle but that is definitely not a circle. If I change it from Circle back to Default then back to Circle it does change the icon but will then reset again at some point later. Not entirely sure how long but probably under an hour. 

Luckily it does seem to only affect the battery icon. You can see the network monitor is still there and works fine and I haven't noticed anything weird with other settings. It worked totally fine before updating to Pixel Experience 12.1 and AOSPMods 2.0.1 but I'm not sure which one caused it since I updated both on the same day.

**Expected behavior**

The icon should stay a circle.

**Screenshots**

![Screenshot_20220825-060704_Camera](https://user-images.githubusercontent.com/12601452/186673051-61f79956-2679-47e8-983a-2ceb70059f94.png)

 - Device: OnePlus 5T
 - OS: Pixel Experience 12.1

**LSPosed Log**

[modules_1974-09-16T15:48:37.62.log](https://github.com/siavash79/AOSPMods/files/9424967/modules_1974-09-16T15.48.37.62.log)

**Comment by TheFeelTrain** [comment]
After posting this I realized I could test so I tried downgrading to 2.0.0 manually. The icon hasn't changed after about 2 hours so I am pretty confident this is caused by something that changed between 2.0.0 and 2.0.1. 

I will just stay on 2.0.0 for now.

**Comment by siavash79** [comment]
I'll test it soon. Can't imagine why that can be

**Comment by EleoXDA** [comment]
Have had no issue since I set it around 22 hours ago

![Screenshot_20220826-151633.png](https://user-images.githubusercontent.com/27622683/186912157-5b91700e-5f1a-4e69-a26f-d63d08e6f07b.png)

**Comment by TheFeelTrain** [comment]
The other files in the zip don't seem particularly relevant so I'd really prefer not to share everything if it's not necessary. I can see the trace for the battery icon in the modules log file. But if there is another file you're looking for specifically let me know.

<details>

```
[ 2022-08-25T00:41:09.593    10421:  6491:  6491 I/LSPosed-Bridge  ] Loading module sh.siava.AOSPMods from /system/priv-app/AOSPMods/AOSPMods.apk
[ 2022-08-25T00:41:09.690    10421:  6491:  6491 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.XPrefs
[ 2022-08-25T00:41:09.693    10421:  6491:  6491 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.AOSPMods
[ 2022-08-25T00:41:09.697    10421:  6491:  6491 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.ResourceManager
[ 2022-08-25T00:41:09.807    10421:  6491:  6491 I/LSPosed-Bridge  ] AOSPMods Version: 2.0.1
[ 2022-08-25T00:41:09.830    10421:  6491:  6491 I/LSPosed-Bridge  ] AOSPMods Records: 64
[ 2022-08-25T00:41:09.846    10421:  6491:  6491 I/LSPosed-Bridge  ] Start Error Dump
[ 2022-08-25T00:41:09.861    10421:  6491:  6491 I/LSPosed-Bridge  ] Start Error Dump
[ 2022-08-25T00:41:17.762    10168:  2627:  2627 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.NoSuchFieldError: com.android.systemui.battery.BatteryMeterView#mDrawable
	at de.robv.android.xposed.XposedHelpers.lambda$findField$1(Unknown Source:6)
	at de.robv.android.xposed.XposedHelpers.j(Unknown Source:0)
	at de.robv.android.xposed.d.get(Unknown Source:28)
	at java.util.Optional.orElseThrow(Optional.java:286)
	at de.robv.android.xposed.XposedHelpers.findField(Unknown Source:21)
	at de.robv.android.xposed.XposedHelpers.getObjectField(Unknown Source:4)
	at sh.siava.AOSPMods.systemui.BatteryStyleManager.updatePrefs(BatteryStyleManager.java:101)
	at sh.siava.AOSPMods.XPrefs.loadEverything(XPrefs.java:47)
	at sh.siava.AOSPMods.XPrefs.lambda$static$0(XPrefs.java:23)
	at sh.siava.AOSPMods.XPrefs$$ExternalSyntheticLambda0.onSharedPreferenceChanged(Unknown Source:0)
	at com.crossbowffs.remotepreferences.RemotePreferences$PreferenceContentObserver.onChange(RemotePreferences.java:522)
	at android.database.ContentObserver.onChange(ContentObserver.java:169)
	at android.database.ContentObserver.onChange(ContentObserver.java:187)
	at android.database.ContentObserver.onChange(ContentObserver.java:202)
	at android.database.ContentObserver.lambda$dispatchChange$0$ContentObserver(ContentObserver.java:282)
	at android.database.ContentObserver$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

```
[ 2022-08-25T01:07:53.884    10168:  6586:  6586 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'void sh.siava.AOSPMods.utils.batteryStyles.BatteryDrawable.setPowerSaveEnabled(boolean)' on a null object reference
	at sh.siava.AOSPMods.systemui.BatteryStyleManager$6$2.afterHookedMethod(BatteryStyleManager.java:248)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.onPowerSaveChanged(Unknown Source:15)
	at com.android.systemui.statusbar.policy.BatteryControllerImpl.addCallback(BatteryControllerImpl.java:157)
	at com.google.android.systemui.statusbar.policy.BatteryControllerImplGoogle.addCallback(Unknown Source:0)
	at com.google.android.systemui.statusbar.policy.BatteryControllerImplGoogle.addCallback(Unknown Source:2)
	at com.android.systemui.battery.BatteryMeterViewController.onViewAttached(BatteryMeterViewController.java:133)
	at com.android.systemui.util.ViewController$1.onViewAttachedToWindow(ViewController.java:52)
	at com.android.systemui.util.ViewController.init(ViewController.java:80)
	at com.android.systemui.statusbar.phone.fragment.dagger.StatusBarFragmentComponent.init(StatusBarFragmentComponent.java:60)
	at org.pixelexperience.systemui.dagger.DaggerSysUIGoogleGlobalRootComponent$SysUIGoogleSysUIComponentImpl$StatusBarComponentImpl$StatusBarFragmentComponentImpl.init(Unknown Source:0)
	at com.android.systemui.statusbar.phone.fragment.CollapsedStatusBarFragment.onViewCreated(CollapsedStatusBarFragment.java:200)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.onViewCreated(Unknown Source:14)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1313)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
	at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3009)
	at android.app.FragmentController.dispatchStart(FragmentController.java:196)
	at com.android.systemui.fragments.FragmentHostManager.createFragmentHost(FragmentHostManager.java:98)
	at com.android.systemui.fragments.FragmentHostManager.reloadFragments(FragmentHostManager.java:219)
	at com.android.systemui.fragments.FragmentHostManager.onConfigurationChanged(FragmentHostManager.java:157)
	at com.android.systemui.fragments.FragmentService$FragmentHostState.handleSendConfigurationChange(FragmentService.java:168)
	at com.android.systemui.fragments.FragmentService$FragmentHostState.lambda$sendConfigurationChange$0(FragmentService.java:160)
	at com.android.systemui.fragments.FragmentService$FragmentHostState.$r8$lambda$GTODP_uYHSkUpHCZ-v1oU22BpWU(Unknown Source:0)
	at com.android.systemui.fragments.FragmentService$FragmentHostState$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

</details>

As for your second question I apologize I'm not exactly sure what you're trying to ask. But the log file covers over 24 hours and the icon reset multiple times in that period so it should be recorded if that's what you mean.

**Comment by siavash79** [comment]
Is it PE+ or normal?

**Comment by EleoXDA** [comment]
> The other files in the zip don't seem particularly relevant so I'd really prefer not to share everything if it's not necessary. I can see the trace for the battery icon in the modules log file. But if there is another file you're looking for specifically let me know.
> 
> As for your second question I apologize I'm not exactly sure what you're trying to ask. But the log file covers over 24 hours and the icon reset multiple times in that period so it should be recorded if that's what you mean.

The thing is I have pixel stock firmware with android 13 (w.r.to your 12) and for more than 24 hours I have been using battery icon.

Which means the issue could only be in android 12 version - if there is any issue.

This begs the question why are you hiding log details - the information that is selected by LSposed app to be shared for developers. I cannot see your device name, rom name, magisk modules, xposed modules and etc other than your provided details (which are only android version and device name).

For me this is a hinderance. But it is your decision.

**Comment by TheFeelTrain** [comment]
> This begs the question why are you hiding log details 

Like I said I just didn't want to share anything beyond what is necessary, that's all. Like you say the logs are made to be shared with developers but this is a public page, any random person can view them not just the developers. I don't think it's that weird to not want to publicly post my device's info/logs. But anyways since you do need it here it is.

[LSPosed_2022-08-25T06_03_22.905.zip](https://github.com/siavash79/AOSPMods/files/9435338/LSPosed_2022-08-25T06_03_22.905.zip)

> Is it PE+ or normal?

It is the Plus version so that might be the issue. If it didn't work at all in the first place I would just consider it an issue with Plus but since 2.0.0 does work it seems like it should be working. Although I understand if you don't want to support Plus. If that's the case I apologize for wasting your time, I can remain on 2.0.0 indefinitely since it does everything I want it to do.

**Comment by siavash79** [comment]
If you're certain that the problem is the transition from 2.0.0 to 2.0.1, I can try to focus on those changes.

It's also interesting that having the errors you sent here, you had your battery changed even with a short period of time

Anyway I'll look at it when I could

**Comment by TheFeelTrain** [comment]
I just realized I should try upgrading to 2.0.1 again and see if it still happens just to double check. There's a possibility uninstalling and reinstalling is enough to fix it.

**Comment by TheFeelTrain** [comment]
Alright I doubled checked and it is definitely something with 2.0.1 specifically. I have been running 2.0.0 with no issues for over 24 hours and then after upgrading to 2.0.1 the icon reset within 10 minutes.

![Screenshot_20220826-114312_AOSP Mods](https://user-images.githubusercontent.com/12601452/186971462-e928c109-a381-4e01-a753-e700a02bd1d5.png)

I saved the logs as soon as I noticed it so the "event" should happen just a few seconds before the end.
[LSPosed_2022-08-26T11_40_17.258.zip](https://github.com/siavash79/AOSPMods/files/9435713/LSPosed_2022-08-26T11_40_17.258.zip)

**Comment by EleoXDA** [comment]
> I upgraded to 2.0.1 again and within 10 minutes the icon had reset. Since I was focused on it this time I realized it happened right after going into fullscreen on YouTube. I downgraded to 2.0.0 and tried to watch a fullscreen video and sure enough it happened again. I thought it might be related to the screen rotating so I tried rotating the screen with no video and it happened again (also on 2.0.0). So the issue is both unrelated to the app version, and is not random.
> 
> I have auto rotate off so I was only experiencing it after watching fullscreen video and the reason it hadn't happened again is I simply hadn't watched any videos in the last 24 hours. This definitely did not happen on Pixel Experience 12.0 so it I am fairly confident it is something with 12.1
> 
> ![Screenshot_20220826-114312_AOSP Mods](https://user-images.githubusercontent.com/12601452/186971462-e928c109-a381-4e01-a753-e700a02bd1d5.png)
> 
> I saved the logs as soon as I noticed it so the "event" should happen just a few seconds before the end. [LSPosed_2022-08-26T11_40_17.258.zip](https://github.com/siavash79/AOSPMods/files/9435713/LSPosed_2022-08-26T11_40_17.258.zip)

Still not reproducible in android 13. Battery is not resetting. And our test group also has no such issue. Could be something related to old device support in custom ROM... I remember we had huge issues with Samsung Galaxy Note3 when adapting it to Android 10 ROMs.

**Comment by siavash79** [comment]
Look for the fix in the next canary (125)

**Comment by TheFeelTrain** [comment]
Now testing canary 126. If I go into landscape the icon still reverts to default, but I do get the circle if I pull the quick menu down. You can see in the video the icon is default but in the pull-down it is the circle. So I assume that is what the change affected.

https://user-images.githubusercontent.com/12601452/187310706-1493eb37-700c-4e08-a55f-5edcb27e97bf.mp4

Not sure if this is helpful but I also took a video of the icon resetting just so you have a visual.

https://user-images.githubusercontent.com/12601452/187311173-c1ded22b-aa20-4b2d-949b-26dc98a8582b.mp4

Starts a circle -> switch landscape resets to default -> back to portrait it stays default

**Comment by EleoXDA** [comment]
Again, no issue on pixel with stock firmware on android 13
