### ISSUE TITLE
[Bug] Lightning symbol missing in circle battery indicator when slow charging

### ISSUE THREAD

**Issue by bdr99** [siavash79/AOSPMods#448]
### Describe the issue

When the circle battery indicator is enabled and I plug in the phone with a slow charger, the lightning symbol does not appear. It only appears when a fast charger is used. This is different from the stock battery symbol, which has no such requirement. This behavior is not intuitive and is different from what users would expect.

### Steps to reproduce

1. Enable the circle battery indicator in AOSP Mods.
2. Plug in the phone using a slow charger.

See below screenshot which shows "Charging" but no lightning symbol.

![Screenshot_20221118-005403](https://user-images.githubusercontent.com/2292715/202632443-92333344-c5b4-413d-bb93-6ec45f1df5fe.png)

### Expected bahavior

I would expect the lightning symbol to always be present when the phone is plugged in, just like the stock battery icon.

### Your device setup (Please take some time to give correct information here)

Pixel 7
Stock Android 13 TD1A.220804.031
October 5, 2022 security update
Magisk 25.2
Root access granted only to AOSP Mods
Magisk modules: Zygisk LSPosed 1.8.5, AOSP Mods 2.4.0
I have no other LSPosed modules.

Please let me know if any other info is needed.

### Logs

```
----part 1 start----
[ 2022-11-17T20:42:15.496     1000:  1581:  1581 I/LSPosed-Bridge  ] Loading module sh.siava.AOSPMods from /system/priv-app/AOSPMods/AOSPMods.apk
[ 2022-11-17T20:42:15.532     1000:  1581:  1581 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.XPrefs
[ 2022-11-17T20:42:15.535     1000:  1581:  1581 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.AOSPMods
[ 2022-11-17T20:42:15.537     1000:  1581:  1581 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.ResourceManager
[ 2022-11-17T20:42:18.762    10219:  1902:  1902 I/LSPosed-Bridge  ] Loading module sh.siava.AOSPMods from /system/priv-app/AOSPMods/AOSPMods.apk
[ 2022-11-17T20:42:18.799    10219:  1902:  1902 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.XPrefs
[ 2022-11-17T20:42:18.807    10219:  1902:  1902 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.AOSPMods
[ 2022-11-17T20:42:18.812    10219:  1902:  1902 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.ResourceManager
[ 2022-11-17T20:42:18.884    10219:  1902:  1902 I/LSPosed-Bridge  ] AOSPMods Version: 2.4.0
[ 2022-11-17T20:42:18.933    10416:  1959:  1959 I/LSPosed-Bridge  ] Loading module sh.siava.AOSPMods from /system/priv-app/AOSPMods/AOSPMods.apk
[ 2022-11-17T20:42:18.970    10416:  1959:  1959 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.XPrefs
[ 2022-11-17T20:42:18.978    10416:  1959:  1959 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.AOSPMods
[ 2022-11-17T20:42:18.984    10416:  1959:  1959 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.ResourceManager
[ 2022-11-17T20:42:19.053    10416:  1959:  1959 I/LSPosed-Bridge  ] AOSPMods Version: 2.4.0
[ 2022-11-17T20:42:19.060    10416:  1959:  1959 I/LSPosed-Bridge  ] AOSPMods Records: 98
[ 2022-11-17T20:42:19.084    10219:  1902:  1902 I/LSPosed-Bridge  ] AOSPMods Records: 98
[ 2022-11-17T20:42:19.469     1000:  1581:  1581 I/LSPosed-Bridge  ] AOSPMods Version: 2.4.0
[ 2022-11-17T20:42:19.471     1000:  1581:  1581 I/LSPosed-Bridge  ] AOSPMods Records: 98
[ 2022-11-17T20:42:19.704     1001:  2220:  2220 I/LSPosed-Bridge  ] Loading module sh.siava.AOSPMods from /system/priv-app/AOSPMods/AOSPMods.apk
[ 2022-11-17T20:42:19.812     1001:  2220:  2220 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.XPrefs
[ 2022-11-17T20:42:19.816     1001:  2220:  2220 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.AOSPMods
[ 2022-11-17T20:42:19.818     1001:  2220:  2220 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.ResourceManager
[ 2022-11-17T20:42:19.940     1001:  2220:  2220 I/LSPosed-Bridge  ] AOSPMods Version: 2.4.0
[ 2022-11-17T20:42:19.942     1001:  2220:  2220 I/LSPosed-Bridge  ] AOSPMods Records: 98
[ 2022-11-17T20:42:20.381    10210:  2593:  2593 I/LSPosed-Bridge  ] Loading module sh.siava.AOSPMods from /system/priv-app/AOSPMods/AOSPMods.apk
[ 2022-11-17T20:42:20.422    10210:  2593:  2593 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.XPrefs
[ 2022-11-17T20:42:20.424    10210:  2593:  2593 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.AOSPMods
[ 2022-11-17T20:42:20.426    10210:  2593:  2593 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.ResourceManager
[ 2022-11-17T20:42:20.482    10210:  2593:  2593 I/LSPosed-Bridge  ] AOSPMods Version: 2.4.0
[ 2022-11-17T20:42:20.484    10210:  2593:  2593 I/LSPosed-Bridge  ] AOSPMods Records: 98
[ 2022-11-18T00:25:51.439    10416: 29522: 29522 I/LSPosed-Bridge  ] Loading module sh.siava.AOSPMods from /system/priv-app/AOSPMods/AOSPMods.apk
[ 2022-11-18T00:25:51.516    10416: 29522: 29522 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.XPrefs
[ 2022-11-18T00:25:51.529    10416: 29522: 29522 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.AOSPMods
[ 2022-11-18T00:25:51.532    10416: 29522: 29522 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.ResourceManager
[ 2022-11-18T00:25:51.732    10416: 29522: 29522 I/LSPosed-Bridge  ] AOSPMods Version: 2.4.0
[ 2022-11-18T00:25:51.761    10416: 29522: 29522 I/LSPosed-Bridge  ] AOSPMods Records: 98
[ 2022-11-18T00:54:03.124    10219:  7040:  7040 I/LSPosed-Bridge  ] Loading module sh.siava.AOSPMods from /system/priv-app/AOSPMods/AOSPMods.apk
[ 2022-11-18T00:54:03.208    10219:  7040:  7040 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.XPrefs
[ 2022-11-18T00:54:03.210    10219:  7040:  7040 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.AOSPMods
[ 2022-11-18T00:54:03.212    10219:  7040:  7040 I/LSPosed-Bridge  ]   Loading class sh.siava.AOSPMods.ResourceManager
[ 2022-11-18T00:54:03.271    10219:  7040:  7040 I/LSPosed-Bridge  ] AOSPMods Version: 2.4.0
[ 2022-11-18T00:54:03.275    10219:  7040:  7040 I/LSPosed-Bridge  ] AOSPMods Records: 98
```

**Comment by EleoXDA** [comment]
Change your charger and/or cable. Probably it stops charging intermittently so that the text of "charging" doesnt disappear, but lightning symbol disappears. Cannot reproduce on my end. 

And no. These are not the "LSposed logs" we ask. To get the real LSposed logs, you will see a "floppy disc" sign at top right position on the screen where you saw these logs. Once you click on it and save that zip file to your storage, you should have attached that one. These logs you shared don't mean anything.

**Comment by EleoXDA** [comment]
> ### Describe the issue
> 
> When the circle battery indicator is enabled and I plug in the phone, the lightning symbol is not consistently present inside the circle battery indicator. Instead, it intermittently appears and disappears every minute or so.
> 
> ### Steps to reproduce
> 
> 1. Enable the circle battery indicator in AOSP Mods.
> 2. Plug in the phone.
> 
> See below screenshot which shows "Charging" but no lightning symbol.
> 
> ![Screenshot_20221118-005403](https://user-images.githubusercontent.com/2292715/202632443-92333344-c5b4-413d-bb93-6ec45f1df5fe.png)
> 
> 
> ### Expected bahavior
> 
> I would expect the lightning symbol to always be present when the phone is plugged in.
> 
> ### Your device setup (Please take some time to give correct information here)
> 
> Pixel 7
> Stock Android 13 TD1A.220804.031
> October 5, 2022 security update
> Magisk 25.2
> Root access granted only to AOSP Mods
> Magisk modules: Zygisk LSPosed 1.8.5, AOSP Mods 2.4.0
> I have no other LSPosed modules.
> 
> Please let me know if any other info is needed.
> 

Any additional info?

**Comment by siavash79** [comment]
It's most probable that the issue is with your charger, as the lightning symbol is in sync with the system battery symbol.

Best way to test it is by using the default battery style and check whether it happens there as well.

**Comment by bdr99** [comment]
Thanks @EleoXDA and @siavash79 for the reply. I'll do some testing with other chargers and also with the system battery symbol, and update here when I have more info.

**Comment by bdr99** [comment]
I did some more testing and here is what I found:
1. I tried with a total of 4 chargers, 2 are USB-A to USB-C, and the other 2 are USB-C with PD. Both USB-A to USB-C chargers consistently had the issue, and both USB-C PD chargers did not have the issue.
2. The issue does not occur when the default (stock) battery symbol is used. It only happens with the circle battery symbol. It is consistently reproducible as long as the circle battery symbol is selected and I'm using a USB-A to USB-C charger.

Item 1 above would suggest a possible issue with the charger, but that doesn't seem possible since everything works perfectly when I use the default battery symbol. Please see the below screen capture where I plug in my phone and unplug it 3 times with the default battery symbol, and the lightning bolt icon works. Then I switch to the circle battery symbol and repeat the experiment, and it fails every time.

https://user-images.githubusercontent.com/2292715/202979404-bb57958b-190d-49fe-89d5-b9da321d171b.mp4

**Comment by EleoXDA** [comment]
> I did some more testing and here is what I found:
> 1. I tried with a total of 4 chargers, 2 are USB-A to USB-C, and the other 2 are USB-C with PD. Both USB-A to USB-C chargers consistently had the issue, and both USB-C PD chargers did not have the issue.
> 2. ...It is consistently reproducible as long as the circle battery symbol is selected and I'm using a USB-A to USB-C charger.
> 

If I understood correctly,
A) usb-a to c chargers --> issue reproducible
B) usb c chargers --> issue is not reproducible

Judging by the fact that you own pixel 7 that comes with one usb-c to usb-c cable, with usb-a to c chargers you use a different cable. And with those you can reproduce the issue. It means they charge slow

When using original usb-c to c cable, you cannot reproduce the issue. It means they charge fast.
I think you cracked the code. Use original cable.

I for one am using usb c charger from my pixel 3aXL box and usb c cable from pixel 6 box. And cannot reproduce the issue you are having.

Let me explain what happens in the video. But before that, please check the description of circle battery:
![Screenshot_20221121-075919.png](https://user-images.githubusercontent.com/27622683/202985322-1e4eae54-3bf1-4574-91cd-dc3ec14479ea.png)

It does NOT indicate charging, it ONLY indicates FAST charging.

Your usba to c chargers CANNOT deliver fast charging.
Your usbc to c chargers CAN deliver fast charging.

This was just an oversight for you.

**Comment by bdr99** [comment]
Hi @EleoXDA,

Thanks for the reply. Sorry, but I don't understand what you are trying to say about the "Indicate fast charging" setting. Would you mind clarifying a couple of points for me?

1. The charging indicator is missing only when I use a slow charger. It works fine when I am fast charging. Why would a setting named "Indicate fast charging" fix that? The problem is specific to when I am _not_ fast charging.
2. Isn't the purpose of the "Indicate fast charging" setting to change the battery symbol to a different color during fast charging? That's not what I'm trying to do, I'm just trying to make the circle battery to behave the same as the stock battery -- display a lighting bolt when charging, regardless of the charging speed.

**Comment by EleoXDA** [comment]
You just need to use a fast enough charger and then it will show up. Chargers below 1200ma don't show up. See below
![Screenshot_20221122-070416.png](https://user-images.githubusercontent.com/27622683/203237309-38d49f84-90f9-43c9-9ef9-82b549667881.png)
![Screenshot_20221122-070416.png](https://user-images.githubusercontent.com/27622683/203237325-2fc12dbf-213e-4f22-998c-4dd6839920c7.png)

**Comment by EleoXDA** [comment]
> Ok thanks for clarifying. I have updated the issue title and description now that we have a better understanding of this bug.


Fixed in latest canary 
![Screenshot_20221122-121608.png](https://user-images.githubusercontent.com/27622683/203301332-9845ec19-7d74-4956-8dbb-78a3157238ae.png)
![Screenshot_20221122-121620.png](https://user-images.githubusercontent.com/27622683/203301380-b40502d9-c47e-4913-82dd-ad381d3944f7.png)

**Comment by bdr99** [comment]
Thanks @siavash79 and @EleoXDA for the fix! I tested the new canary version and it's working much better now. I do have a few observations:
1. When I plug in the charger, the charging icon in the circle battery symbol briefly flickers. After it initially appears, it briefly disappears and appears again.
2. I am still getting no charging icon during wireless charging. This behavior is the same as 2.4.0.

Should I open a separate issue for these observations, or should we reopen this one?

**Comment by EleoXDA** [comment]
> Thanks @siavash79 and @EleoXDA for the fix! I tested the new canary version and it's working much better now. The issue with the charging symbol missing during slow charging is fixed. But I do have a few observations:
> 1. When I plug in the charger, the charging icon in the circle battery symbol briefly flickers. After it initially appears, it briefly disappears and appears again. This flickering does not happen with the stock battery symbol.
> 2. I am getting no charging icon in the circle battery symbol during wireless charging. The charging icon works fine during wireless charging with the stock battery symbol. This behavior is the same as 2.4.0.
> 
> Should I open a separate issue for these observations, or should we reopen this one?

1) I still cannot reproduce your behavior. With both slow or fast charger. You probably should send us your charger and cable as even my charger from 2014 doesn't make it.
2) I myself do not own a wireless charger as they are not environmentally friendly. Maybe one of our contributors owns it and can maybe test it.

@siavash79 is in a long travel now. He will be available this weekend.

We will continue from this issue.

In the meantime please send us a video showing the flicker(1)

**Comment by bdr99** [comment]
Sure, here is a video showing the flickering. In the video, I plug and unplug my charger 3 times. It happens with all of my chargers, regardless of whether it is a fast or slow charger. Please let me know if I can help with any testing.

https://user-images.githubusercontent.com/2292715/203483438-565701b0-a6df-4ff7-8d69-32489dfabb68.mp4

**Comment by bdr99** [comment]
By the way, do you have a phone with the "battery share" feature? If so, maybe that can help you test the wireless charging issue. Just an idea.

**Comment by EleoXDA** [comment]
> Sure, here is a video showing the flickering. In the video, I plug and unplug my charger 3 times. It happens with all of my chargers, regardless of whether it is a fast or slow charger. Please let me know if I can help with any testing.
> 
> https://user-images.githubusercontent.com/2292715/203483438-565701b0-a6df-4ff7-8d69-32489dfabb68.mp4

If you rewind, you will see that from three attempts, first one did NOT flicker, but other two did.

Please tell us the difference between the first one and last two

**Comment by EleoXDA** [comment]
> By the way, do you have a phone with the "battery share" feature? If so, maybe that can help you test the wireless charging issue. Just an idea.

I have. But I have no other device to share the battery with. None of my other devices have wireless charging abilities

**Comment by bdr99** [comment]
> If you rewind, you will see that from three attempts, first one did NOT flicker, but other two did.
> 
> Please tell us the difference between the first one and last two

I didn't do anything differently between the first one and the last two. The issue is intermittent, it happens about 50% of the time.

> If you ask me it looks like the contacts were not made good with charging house for the last two attempts.

Then why doesn't it happen with the stock battery symbol? I have tried over 100 times and have not seen the issue even once with the stock battery symbol. It happens 50% of the time with the circle battery symbol.

In case this helps to reproduce the issue, it seems to happen more often on the first charge after a restart. I'm able to reproduce the issue fairly reliably by restarting SystemUI using the option in the AOSP Mods app, and then plugging in the phone right after that.

**Comment by EleoXDA** [comment]
> I didn't do anything differently between the first one and the last two. The issue is intermittent, it happens about 50% of the time.

We can't fix something that happens 50% of the time. In that case, please navigate to LSposed logs (see my screenshots below to understand how to actually get LSposed logs that we require), and checkout the full logs to see differences between the charging attempts (you can record the timestamps

![Screenshot_20221124-072526.png](https://user-images.githubusercontent.com/27622683/203709780-e9ee7567-54f1-434e-97d8-25e23b06845f.png)
![Screenshot_20221124-072541.png](https://user-images.githubusercontent.com/27622683/203709810-f32fe720-32f5-42be-ae61-493d6e0e0644.png)
![Screenshot_20221124-072623.png](https://user-images.githubusercontent.com/27622683/203709830-6936b447-e380-4dd1-b1d2-e9ca88fbd8f3.png)

> Then why doesn't it happen with the stock battery symbol? I have tried over 100 times and have not seen the issue even once with the stock battery symbol. It happens 50% of the time with the circle battery symbol.
> 
> In case this helps to reproduce the issue, it seems to happen more often on the first charge after a restart. I'm able to reproduce the issue fairly reliably by restarting SystemUI using the option in the AOSP Mods app, and then plugging in the phone right after that.
> 

I am still going with your screenrecord, as it is the only reproduction I have observed of said event, which seems to happen AFTER first successful trial of charging, rather than after reboot. But still, we either need to see the action on our devices as well (but we can also not reproduce on our devices) or we need to find what happens when it happens in logs. Could you try the method above to extract LSposed logs and tell me what you see in full logs at the time period when you do it?

**Comment by bdr99** [comment]
Hi @EleoXDA,

In order to get the best chance of replicating the issue, I'd suggest these steps:

1. Unplug the phone and drain the battery to less than 50%
2. Enable the circle battery indicator in AOSP Mods
3. Restart SystemUI using the option in AOSP Mods
4. Plug in the phone

In case that doesn't work, hopefully these logs will help. The first attachment shows what was logged to full.log on an occasion when the flickering didn't happen, and the second is from a time when the flickering did happen.

[charger_connected_no_flickering.log](https://github.com/siavash79/AOSPMods/files/10096732/charger_connected_no_flickering.log)

[charger_connected_flickering.log](https://github.com/siavash79/AOSPMods/files/10096733/charger_connected_flickering.log)

**Comment by EleoXDA** [comment]
> Hi @EleoXDA,
> 
> In order to get the best chance of replicating the issue, I'd suggest these steps:
> 
> 1. Unplug the phone and drain the battery to less than 50%
> 2. Enable the circle battery indicator in AOSP Mods
> 3. Restart SystemUI using the option in AOSP Mods
> 4. Plug in the phone
> 
> In case that doesn't work, hopefully these logs will help. The first attachment shows what was logged to full.log on an occasion when the flickering didn't happen, and the second is from a time when the flickering did happen.
> 
> [charger_connected_no_flickering.log](https://github.com/siavash79/AOSPMods/files/10096732/charger_connected_no_flickering.log)
> 
> [charger_connected_flickering.log](https://github.com/siavash79/AOSPMods/files/10096733/charger_connected_flickering.log)
> 

I did follow your steps one by one, i.e. charge below 50%, enabled circled battery, restarted systemUI and plugged charger (in exact this order) but I couldn't reproduce the event.
https://user-images.githubusercontent.com/27622683/204102545-a43eb521-7ad8-4520-a2c3-ab1b9140c546.mp4

Could you please share the full lsposed.zip files for both of the cases you shared above? I am guessing you extracted these from zip files and you still have the zip files.

**Comment by bdr99** [comment]
Sure. The first two logs were captured immediately before and immediately after connecting a charger, when the flickering did happen. The next two logs were captured on a time when the flickering did not happen. They are not the exact same logs that I shared above, but they were created in the same way. Hope this helps.

[flickering_before_connecting_charger.zip](https://github.com/siavash79/AOSPMods/files/10097217/flickering_before_connecting_charger.zip)
[flickering_after_connecting_charger.zip](https://github.com/siavash79/AOSPMods/files/10097216/flickering_after_connecting_charger.zip)
[no_flickering_before_connecting_charger.zip](https://github.com/siavash79/AOSPMods/files/10097219/no_flickering_before_connecting_charger.zip)
[no_flickering_after_connecting_charger.zip](https://github.com/siavash79/AOSPMods/files/10097218/no_flickering_after_connecting_charger.zip)

**Comment by EleoXDA** [comment]
Again, cannot reproduce the "symbol disappearing" issue even with my old charger. If you comment on my video, I plugged in and then plugged out the charger.

I will check logs to see whether there is anything pointing to it.

**Comment by bdr99** [comment]
OK, thanks. Let me know if I can help in any other way. By the way, would you mind reopening this issue, since we are using it to track the two pending issues?

**Comment by EleoXDA** [comment]
Once we figure out the issue is reproducible, I will reopen it
